name: Test Create Tag Action

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Delete the tag if it exists
      - name: Delete Tag if Exists
        run: |
          TAG_NAME="Test-1.2.3"
          EXISTING_TAG=$(git ls-remote --tags origin | grep -o "refs/tags/$TAG_NAME" || true)
          if [ -n "$EXISTING_TAG" ]; then
            echo "Deleting existing tag: $TAG_NAME"
            git push --delete origin "$TAG_NAME"
          else
            echo "Tag $TAG_NAME does not exist, no deletion needed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Use the Create Tag Action
      - name: Use Create Tag Action
        id: test_created_tag
        uses: ./
        with:
          tag_name: "Test-1.2.3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check and Print the Output
        run: |
          if [ "${{ steps.test_created_tag.outputs.created_tag }}" == "Test-1.2.3" ]; then
            echo "The created tag is Test-1.2.3."
          else
            echo "The created tag is not Test-1.2.3. It is: ${{ steps.test_created_tag.outputs.created_tag }}"
            exit 1
          fi
        shell: bash

      # Step 4: Delete the tag if it exists
      - name: Clean Up Tag
        run: |
          TAG_NAME="Test-1.2.3"
          EXISTING_TAG=$(git ls-remote --tags origin | grep -o "refs/tags/$TAG_NAME" || true)
          if [ -n "$EXISTING_TAG" ]; then
            echo "Deleting existing tag: $TAG_NAME"
            git push --delete origin "$TAG_NAME"
          else
            echo "Tag $TAG_NAME does not exist, no deletion needed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
